# =========================================================================
# ===                  CONFIGURATION GLOBALE (COMMUNE)                  ===
# =========================================================================
server:
  port: 8082

spring:
  application:
    name: job_tracker

  # Configuration JPA par défaut
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

# -------------------------------------------------------------------------
#  MONITORING / ACTUATOR (Doit être ici pour être actif partout !)
# -------------------------------------------------------------------------
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: job-tracker-backend

---
# =========================================================================
# ===                  PROFIL PAR DÉFAUT (DEV LOCAL)                    ===
# =========================================================================
spring:
  config:
    activate:
      on-profile: default

  datasource:
    url: jdbc:postgresql://localhost:5432/job_tracker
    username: postgres
    password: emsi
    driver-class-name: org.postgresql.Driver

---
# =========================================================================
# ===              PROFIL PRODUCTION (DOCKER / K8S)                     ===
# =========================================================================
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    # Dans K8s, on surcharge souvent username/password via les variables d'environnement (ENV)
    # Mais on définit l'URL ici.
    url: jdbc:postgresql://postgres-db:5432/job_tracker
    driver-class-name: org.postgresql.Driver